### ISSUE TITLE
Installing "nodejs-mobile-cordova" for android failed

### ISSUE THREAD

**Issue by hugetiny** [JaneaSystems/nodejs-mobile-samples#21]
Installing "nodejs-mobile-cordova" for android
Failed to install 'nodejs-mobile-cordova': CordovaError: Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

**Comment by hugetiny** [comment]
in UseNativeModules projects

**Comment by jaimecbernardo** [comment]
Hi @hugetiny ,
What version of cordova and cordova-android are you using?

**Comment by hugetiny** [comment]
@jaimecbernardo I changed my cordova version from 9 to 8.1.2
and it turns out :
Android Studio project detected
Android Studio project detected
Android Studio project detected
Android Studio project detected
Android Studio project detected
Android Studio project detected
ANDROID_HOME=C:\Android\android-sdk\
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_221
Requirements check failed for JDK 1.8

**Comment by hugetiny** [comment]
somehow i succeed to build with cordova 8 and android API 27
but it stuck on 

the emulator console:
```
No target specified and no devices found, deploying to emulator
No target specified and no devices found, deploying to emulator
No target specified and no devices found, deploying to emulator
No emulator specified, defaulting to 768M
No emulator specified, defaulting to 768M
No emulator specified, defaulting to 768M
Waiting for emulator to start...
Waiting for emulator to start...
Waiting for emulator to start...
```

```
emulator: Requested console port 5584: Inferring adb port 5585.
Creating filesystem with parameters:
    Size: 69206016
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 4224
    Inode size: 256
    Journal blocks: 1024
    Label:
    Blocks: 16896
    Block groups: 1
    Reserved block group size: 7
Created filesystem with 11/4224 inodes and 1302/16896 blocks
Hax is enabled
Hax ram_size 0x40000000
HAX is working and emulator runs in fast virt mode.
emulator: Listening for console connections on port: 5584
emulator: Serial number of this emulator (for ADB): emulator-5584
```

**Comment by hugetiny** [comment]
```
  "dependencies": {
    "cordova-android": "^7.1.0",
    "cordova-ios": "^4.5.4",
    "cordova-plugin-whitelist": "^1.3.3",
    "nodejs-mobile-cordova": "^0.3.3"
  },
```
