### ISSUE TITLE
cordova example outdated and non functional

### ISSUE THREAD

**Issue by semidark** [JaneaSystems/nodejs-mobile-samples#31]
I tried to get the cordova example up and running so I can figure out how to build sqlite for my current nodejs-mobile-cordova project wich is using Cordova v10 and node v12. 

To get the Build of the example running I had to downgrade my node Version to the now unsupported version 8 and my Cordova Version to 8.1.2.

After the downgrade, the build process succeeded. But running the app in the Android Emulator failed since the app is only saying "Starting Engine". Pressing the Buttons is not doing anything.

my current System Setup looks like this:

- node: v8.17.0
- npm: 6.13.4
- cordova: 8.1.2 (cordova-lib@8.1.1)

Environment:

- ANDROID_HOME=/home/user/Android/Sdk
- ANDROID_SDK_ROOT=/home/user/Android/Sdk
- JAVA_HOME=/opt/android-studio/jre
- ANDROID_NDK_HOME=/home/user/Android/Sdk/ndk/21.0.6113669

I Think this issue is related: https://github.com/JaneaSystems/nodejs-mobile/issues/301

**Comment by JaosnHsieh** [comment]
try [this hello world example](https://github.com/JaosnHsieh/nodejs-mobile-samples#steps-to-run-hello-word-with-nodejs-mobile-cordova043)

there are some scripts needed changes I found it [here](https://github.com/okhiroyuki/nodejs-mobile-cordova/pull/10/commits/1788d4baf501c7054f97d745b9093a48a1af0ba3) and put them in the above example

**Comment by luweigen** [comment]
@semidark  I failed on the cordova example too. Instead i made the android/native-gradle-node-folder work in [my fork](https://github.com/luweiewul/nodejs-mobile-samples).
