### ISSUE TITLE
Can it run with vuejs?

### ISSUE THREAD

**Issue by xeoshow** [janeasystems/nodejs-mobile-samples#7]
Hello,

I am new to nodejs-mobile-samples, and just would like to know: For the nodejs-mobile, could vuejs projects be supported as well? If yes, and how to pack them into android apk?

Thanks a lot.

Best regards, Jason

**Comment by jaimecbernardo** [comment]
Hi @xeoshow ,
I'm not familiar with vuejs, but from the description I've read it seems like it's an UI HTML+JS framework.

`nodejs-mobile` is to have the nodejs runtime running in the background.

If you are trying to use nodejs-mobile with an app that needs a HTML+JS framework, Cordova might be a good place to start. Check the cordova plugin: https://github.com/janeasystems/nodejs-mobile-cordova

I hope this is helpful.

**Comment by xeoshow** [comment]
Thanks so much for quick reply, yes it is just MVVM framework (HTML+JS). For the vuejs project, it will be finally generated with html, css and js files. For those files, how could I set them as the www root , so  can access them via url like "http://localhost:8000"? 

I tried to find the related wikis or documents but with no luck, thanks in advance for further help!

Best regards, Jason

**Comment by xeoshow** [comment]
Vuejs is just something similar to angularjs, so I just study below example should be most similar?
https://github.com/janeasystems/nodejs-mobile-samples/tree/master/cordova-angularjs

Thanks a lot.

Best regards, Jason

**Comment by xeoshow** [comment]
I use the generated html/css/js files by vue, and place them in the www folder, this way it works. Thanks for help!
